{% set version = "2.0.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rstantools
  version: {{ version|replace("-", "_") }}

source:
  fn: rstantools_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rstantools_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rstantools/rstantools_{{ version }}.tar.gz
  sha256: 4ae78aa39c3d4897f453e621a09961d6f2cda27a1b5657d4d4b32d3d89bd80c6

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.16
    - r-desc
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.16
    - r-desc

test:
  commands:
    - $R -e "library('rstantools')"           # [not win]
    - "\"%R%\" -e \"library('rstantools')\""  # [win]

about:
  home: http://mc-stan.org/, http://discourse.mc-stan.org
  license: GPL (>= 3)
  summary: Provides various tools for developers of R packages interfacing with
    'Stan' <http://mc-stan.org>, including functions to set up the required package structure,
    S3 generics and default methods to unify function naming across 'Stan'-based R packages,
    and a vignette with recommendations for developers.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
