travis:
  secure:
    BINSTAR_TOKEN: Ag/TzrTeUUaaYUXW7ARuTg/FwWQ8HY+c/c9ciIz4W0mhkPu8ZnO6amrsoLBcclo4LrWBlIhFsSZeNQpuSWlWT3jn9lM5PrULmgrIhyldmF+y/5PkMJ44j9710qV5kJrGKfWTtJeGwrPBxkUS/BbiQlNlx0RH52Gpp6TbQH3wUuG4GB2lTuYFhD87ODIHd6hvmUxGR3a/ZwUt91K36Gi55QTmHnrpomiKORGCbPUolnQS459eFceMSjG2K5ntYGsgiDTAKshGMw/q2J+TRXZSc2q1ydMyFkvQbnGmX7kswe8lZvDjKAA1Yyweni1pgAzPsw3lZjaxU8E6M/lJHnZ6LvJ+QXVjuG4LzyrYoxstT2Jpp4IorLYXrG45Ob8ab6lETUomEAW8d+9sP/61XeerDN1FybwYWdEGAtgYOZ82n4G2GGjbvVX1rveKwBZWKsY9HzCw8vxY746AarAfUteJdEkSqgUNlvETzdFvDdRwEjfJDSOvPJucMWii+c9pEvte3eYdFFCuQTofX36+O5VYhSXLeQEpLA4YPEFdrF9ivN3f0yiTBMlYAoU4MeM1kCKsupRQx01bIF1KxdCwte5YAZl61hk0cZL/6KVtKnEQXSrUFFrprzFazth4gr+ukYdDUzb8kvUR2oscYyRmOZ2rvdUddraQNWXVGvDVRvPgfxs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
